# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake

# The command to remove a file.
RM = /mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/n9751041/little_owls

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/n9751041/little_owls

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Headers\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/mnt/hpccs01/pkg/suse12/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/n9751041/little_owls/CMakeFiles /home/n9751041/little_owls//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/n9751041/little_owls/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runsim

# Build rule for target.
runsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runsim
.PHONY : runsim

# fast build rule for target.
runsim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/build
.PHONY : runsim/fast

#=============================================================================
# Target rules for targets named TinyTIFFShared

# Build rule for target.
TinyTIFFShared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TinyTIFFShared
.PHONY : TinyTIFFShared

# fast build rule for target.
TinyTIFFShared/fast:
	$(MAKE) $(MAKESILENT) -f external/TinyTIFF/src/CMakeFiles/TinyTIFFShared.dir/build.make external/TinyTIFF/src/CMakeFiles/TinyTIFFShared.dir/build
.PHONY : TinyTIFFShared/fast

#=============================================================================
# Target rules for targets named common_tinytiff_test_lib

# Build rule for target.
common_tinytiff_test_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common_tinytiff_test_lib
.PHONY : common_tinytiff_test_lib

# fast build rule for target.
common_tinytiff_test_lib/fast:
	$(MAKE) $(MAKESILENT) -f external/TinyTIFF/tests/common_tinytiff_test_lib/CMakeFiles/common_tinytiff_test_lib.dir/build.make external/TinyTIFF/tests/common_tinytiff_test_lib/CMakeFiles/common_tinytiff_test_lib.dir/build
.PHONY : common_tinytiff_test_lib/fast

#=============================================================================
# Target rules for targets named tinytiffreader_test

# Build rule for target.
tinytiffreader_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinytiffreader_test
.PHONY : tinytiffreader_test

# fast build rule for target.
tinytiffreader_test/fast:
	$(MAKE) $(MAKESILENT) -f external/TinyTIFF/tests/tinytiffreader_test/CMakeFiles/tinytiffreader_test.dir/build.make external/TinyTIFF/tests/tinytiffreader_test/CMakeFiles/tinytiffreader_test.dir/build
.PHONY : tinytiffreader_test/fast

#=============================================================================
# Target rules for targets named tinytiffwriter_test

# Build rule for target.
tinytiffwriter_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinytiffwriter_test
.PHONY : tinytiffwriter_test

# fast build rule for target.
tinytiffwriter_test/fast:
	$(MAKE) $(MAKESILENT) -f external/TinyTIFF/tests/tinytiffwriter_test/CMakeFiles/tinytiffwriter_test.dir/build.make external/TinyTIFF/tests/tinytiffwriter_test/CMakeFiles/tinytiffwriter_test.dir/build
.PHONY : tinytiffwriter_test/fast

#=============================================================================
# Target rules for targets named tinytiffwriter_speedtest

# Build rule for target.
tinytiffwriter_speedtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinytiffwriter_speedtest
.PHONY : tinytiffwriter_speedtest

# fast build rule for target.
tinytiffwriter_speedtest/fast:
	$(MAKE) $(MAKESILENT) -f external/TinyTIFF/tests/tinytiffwriter_speedtest/CMakeFiles/tinytiffwriter_speedtest.dir/build.make external/TinyTIFF/tests/tinytiffwriter_speedtest/CMakeFiles/tinytiffwriter_speedtest.dir/build
.PHONY : tinytiffwriter_speedtest/fast

Environment.o: Environment.cpp.o
.PHONY : Environment.o

# target to build an object file
Environment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Environment.cpp.o
.PHONY : Environment.cpp.o

Environment.i: Environment.cpp.i
.PHONY : Environment.i

# target to preprocess a source file
Environment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Environment.cpp.i
.PHONY : Environment.cpp.i

Environment.s: Environment.cpp.s
.PHONY : Environment.s

# target to generate assembly for a file
Environment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Environment.cpp.s
.PHONY : Environment.cpp.s

Individual.o: Individual.cpp.o
.PHONY : Individual.o

# target to build an object file
Individual.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Individual.cpp.o
.PHONY : Individual.cpp.o

Individual.i: Individual.cpp.i
.PHONY : Individual.i

# target to preprocess a source file
Individual.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Individual.cpp.i
.PHONY : Individual.cpp.i

Individual.s: Individual.cpp.s
.PHONY : Individual.s

# target to generate assembly for a file
Individual.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Individual.cpp.s
.PHONY : Individual.cpp.s

Model.o: Model.cpp.o
.PHONY : Model.o

# target to build an object file
Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Model.cpp.o
.PHONY : Model.cpp.o

Model.i: Model.cpp.i
.PHONY : Model.i

# target to preprocess a source file
Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Model.cpp.i
.PHONY : Model.cpp.i

Model.s: Model.cpp.s
.PHONY : Model.s

# target to generate assembly for a file
Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Model.cpp.s
.PHONY : Model.cpp.s

RandomGenerator.o: RandomGenerator.cpp.o
.PHONY : RandomGenerator.o

# target to build an object file
RandomGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/RandomGenerator.cpp.o
.PHONY : RandomGenerator.cpp.o

RandomGenerator.i: RandomGenerator.cpp.i
.PHONY : RandomGenerator.i

# target to preprocess a source file
RandomGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/RandomGenerator.cpp.i
.PHONY : RandomGenerator.cpp.i

RandomGenerator.s: RandomGenerator.cpp.s
.PHONY : RandomGenerator.s

# target to generate assembly for a file
RandomGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/RandomGenerator.cpp.s
.PHONY : RandomGenerator.cpp.s

RunSim.o: RunSim.cpp.o
.PHONY : RunSim.o

# target to build an object file
RunSim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/RunSim.cpp.o
.PHONY : RunSim.cpp.o

RunSim.i: RunSim.cpp.i
.PHONY : RunSim.i

# target to preprocess a source file
RunSim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/RunSim.cpp.i
.PHONY : RunSim.cpp.i

RunSim.s: RunSim.cpp.s
.PHONY : RunSim.s

# target to generate assembly for a file
RunSim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/RunSim.cpp.s
.PHONY : RunSim.cpp.s

Solar.o: Solar.cpp.o
.PHONY : Solar.o

# target to build an object file
Solar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Solar.cpp.o
.PHONY : Solar.cpp.o

Solar.i: Solar.cpp.i
.PHONY : Solar.i

# target to preprocess a source file
Solar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Solar.cpp.i
.PHONY : Solar.cpp.i

Solar.s: Solar.cpp.s
.PHONY : Solar.s

# target to generate assembly for a file
Solar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Solar.cpp.s
.PHONY : Solar.cpp.s

Wrapper.o: Wrapper.cpp.o
.PHONY : Wrapper.o

# target to build an object file
Wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Wrapper.cpp.o
.PHONY : Wrapper.cpp.o

Wrapper.i: Wrapper.cpp.i
.PHONY : Wrapper.i

# target to preprocess a source file
Wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Wrapper.cpp.i
.PHONY : Wrapper.cpp.i

Wrapper.s: Wrapper.cpp.s
.PHONY : Wrapper.s

# target to generate assembly for a file
Wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/Wrapper.cpp.s
.PHONY : Wrapper.cpp.s

callModel.o: callModel.cpp.o
.PHONY : callModel.o

# target to build an object file
callModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/callModel.cpp.o
.PHONY : callModel.cpp.o

callModel.i: callModel.cpp.i
.PHONY : callModel.i

# target to preprocess a source file
callModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/callModel.cpp.i
.PHONY : callModel.cpp.i

callModel.s: callModel.cpp.s
.PHONY : callModel.s

# target to generate assembly for a file
callModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runsim.dir/build.make CMakeFiles/runsim.dir/callModel.cpp.s
.PHONY : callModel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... TinyTIFFShared"
	@echo "... common_tinytiff_test_lib"
	@echo "... runsim"
	@echo "... tinytiffreader_test"
	@echo "... tinytiffwriter_speedtest"
	@echo "... tinytiffwriter_test"
	@echo "... Environment.o"
	@echo "... Environment.i"
	@echo "... Environment.s"
	@echo "... Individual.o"
	@echo "... Individual.i"
	@echo "... Individual.s"
	@echo "... Model.o"
	@echo "... Model.i"
	@echo "... Model.s"
	@echo "... RandomGenerator.o"
	@echo "... RandomGenerator.i"
	@echo "... RandomGenerator.s"
	@echo "... RunSim.o"
	@echo "... RunSim.i"
	@echo "... RunSim.s"
	@echo "... Solar.o"
	@echo "... Solar.i"
	@echo "... Solar.s"
	@echo "... Wrapper.o"
	@echo "... Wrapper.i"
	@echo "... Wrapper.s"
	@echo "... callModel.o"
	@echo "... callModel.i"
	@echo "... callModel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

